<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- Otimização recomendada para imagens baseadas em Alpine Linux -->
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

</Project>
