apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: dotnet-api-dev
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "4"
    limits.memory: "8Gi"
    pods: "10" # Limita o total de Pods simultâneos
